### ISSUE TITLE
Question - How can I use the font on Photoshop or Sketch?

### ISSUE THREAD

**Issue by LeCoupa** [fizzed/font-mfizz#11]
> I found a solution that works for me. Just download and install the font from Font Awesome website. Then, use the Font Awesome Cheatsheet to copy and paste the icons in Photoshop and Fireworks. (or Illustrator or whatever you'd like to use)
> Works perfectly!

http://superuser.com/questions/532556/how-can-i-use-font-awesome-in-photoshop-and-fireworks

**Comment by ketkoota** [comment]
I haven't checked Photoshop, but in Illustrator, with the font mfizz selected, choose: Window> Type> Glyphs. You'll see all of the icons and you can double click to choose. I agree though, it would be great to have the cheatsheet as well so that you can do a quick find on the page to jump to the correct icon and copy/paste into your software of choice.

**Comment by c4milo** [comment]
A cheatsheet will be really helpful indeed.
