### ISSUE TITLE
Update npm 

### ISSUE THREAD

**Issue by BrunnerLivio** [fizzed/font-mfizz#58]
Hey there! 
Can you please update this package on npm. [Currently, the npm package is on version 1.2.2](https://www.npmjs.com/package/font-mfizz).

**Comment by noraj1337** [comment]
The maintainer of [font-mfizz npm](https://www.npmjs.com/package/font-mfizz) is [exaptis](https://www.npmjs.com/~exaptis) that is no part of the [fizzed org](https://github.com/orgs/fizzed/people). So this is not an official package.

So @jjlauer can you create an official npm package, there is currently a big gap between 1.2.2 and 2.4.2.

**Comment by noraj1337** [comment]
PS : You will need to open [dispute](https://docs.npmjs.com/policies/disputes) with [@exaptis](https://github.com/exaptis).

**Comment by noraj1337** [comment]
I don't know how you push your code to cdnjs but it is possible to run tests, push to CDN, push to npmjs, create a github release with package and changelog automatically from a github tag with a CI tool for example with [Travis](https://docs.travis-ci.com/user/deployment/npm/) or with [CircleCI](https://circleci.com/docs/1.0/npm-continuous-deployment/).

**Comment by exaptis** [comment]
Hi. I didn't mean to take over this package but as there was no npm package maintainer and I needed it on npm quite urgently it just checked it out and published it. I have no problem to hand it over to the original maintainer @jjlauer. 

@BrunnerLivio I published the latest versions, you should now be able to get v2.3.0 from npm, although it does not list as latest release, but if you execute `npm show font-mfizz versions` you get `[ '1.2.0', '1.2.2', '2.0.0', '2.1.0', '2.2.0', '2.3.0' ]`.

Hope this helps. 

Cheers, 
David

**Comment by noraj1337** [comment]
@exaptis Of course, we understand you just wanted to help. May be @jjlauer doesn't want or doesn't have time to maintain this package and will add you in the `Community contributions`.

But `2.3.0` is not the latest release, there is `2.4.0` and `2.4.1`, check https://github.com/fizzed/font-mfizz/releases .

I this it is a waste of time to manually update this kind of package and this is because it is works that you didn't update it since a long time. That's why it will be better if @jjlauer should provide an official package with a CI tool that atomically publish it from each git tag.

**Comment by exaptis** [comment]
@noraj1337 totally agree, this should be build and published automatically. I'd be happy to take a look at this and create a PR with the necessary adjustments, but only in a few weeks as I'm currently on vacation.

I forgot to rebase against the upstream, 2.4.0 and 2.4.1 are now published on npm.

**Comment by noraj1337** [comment]
@exaptis Thanks for your amazing reactivity. Have some good holidays.
